apiVersion: v1
kind: Service
metadata:
  name: videogame-tracker
spec:
  selector:
    app: videogame-tracker
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: videogame-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videogame-tracker
  template:
    metadata:
      labels:
        app: videogame-tracker
        name: webapp
    spec:
      hostname: videogame-tracker
      subdomain: webapp
      containers:
        - name: videogame-tracker
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          image: cooljacob204/videogame-tracker:latest
          ports:
          - name: primary
            containerPort: 3000
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: videogame-tracker
                key: db-username
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: videogame-tracker
                key: db-port
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: videogame-tracker
                key: db-password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: videogame-tracker
                key: db-host
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: videogame-tracker
                key: session-secret